### ISSUE TITLE
gene symbols not being seen with viewPathway calls using openCPU+apache+R3.5+ubuntu18.04

### ISSUE THREAD

**Issue by viswam78** [GuangchuangYu/ReactomePA#16]
I have an issue to report using opencpu 2.0.7 with Ubuntu 18.04, for R version 3.5.
Gene symbols are not being shown using the viewPathway function when using the openCPU. It works fine locally on RStudio using my laptop, but using the opencpu + apache server, somehow the gene symbols are not being shown with the new version of ReactomePA. However, I have to mention that it worked fine with the previous versions of ReactomePA and clusterProfiler, i.e., I was able to see the gene names on the pathway.

This is the call I am using: viewPathway(pathName, organism = colloquialName, readable = TRUE, foldChange = geneList, vertex.label.font = 3, vertex.label.color = "#000000", vertex.label.cex = 1)
I also tried using, just the viewPathway(pathName, organism = colloquialName, readable = TRUE, foldChange = geneList) and a simple viewPathway(pathName) call.

Is this a known issue? These are the ReactomePA and clusterProfiler versions.
Reactome PA 1.24.0
clusterProfiler 3.8.1
DOSE 3.6.0
This is how the geneList looks like:
> head(geneList)
   229700    229706     78935     14317     14025     66356 
 6.305014  3.172351  2.276868  2.212017 -1.810016 -1.938765 
> typeof(geneList)
[1] "double"

**Comment by GuangchuangYu** [comment]
I can't reproduce the issue with Reactome PA 1.24.0 on my PC.

**Comment by viswam78** [comment]
It works fine on my laptop too. However it does not work when I load the package through openCPU using apache server in a ubuntu 18.04 box with the latest R version 3.5. I will see if it has something to do with opencpu configuration etc.

**Comment by viswam78** [comment]
It works fine with R3.5, ReactomePA 1.24.0 and using ubuntu 18.04 and generating an image with R script rather than opencpu calls. So, It seems that it might be openCPU issue or the compatibility of openCPU with either R/ubuntu or a combination. I will close the ticket now and thank you for getting back to me earlier.
