### ISSUE TITLE
No gene can be mapped, return NULL

### ISSUE THREAD

**Issue by ulapei** [GuangchuangYu/ReactomePA#17]
Hi!

I am very new to Reactome and Pathway Analysis. I have a .csv file that contains only gene IDs in the Entrez form. I.e. "23956”, “56277”, “12268”, “20259”, “16157”, “11815". However, whenever I try to run the enrichPathway function, I get the error: 
--> No gene can be mapped....
--> Expected input gene ID: 12491,74030,100502803,27801,12727,208092
--> return NULL...

The organism that I'm working with is mouse and the function I am using is: 
x <- enrichPathway(gene=mydata,organism = "mouse", readable=T)

I have checked the IDs in KEGG and it does recognize the genes and the data associated with it. I'm really struggling to understand what could be causing the issue. Thanks!

I have also tried it with data that includes the logFC and p values, but get the same error.

**Comment by ulapei** [comment]
Solved it by converting the data into values. Thanks, it works now.

**Comment by Dmy1999** [comment]
> 

could you plz be more specific on how to resolve this problem, cause l'm also puzzled here.
