### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by xiaowenchenjax** [GuangchuangYu/ReactomePA#20]
HI, 
When i install this package in R/3.5.1, some issue happened.
BiocManager::install("ReactomePA", version = "3.8")
Bioconductor version 3.8 (BiocManager 1.30.3), R 3.5.1 (2018-07-02)
Installing package(s) 'ReactomePA'
trying URL 'https://bioconductor.org/packages/3.8/bioc/src/contrib/ReactomePA_1.26.0.tar.gz'
Content type 'application/x-gzip' length 3001858 bytes (2.9 MB)
==================================================
downloaded 2.9 MB

* installing *source* package ‘ReactomePA’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
Warning in gzfile(file, "rb") :
  cannot open compressed file '/home/chenx/R/x86_64-pc-linux-gnu-library/3.5/graphite/R/sysdata.rdx', probable reason 'No such file or directory'
Error in gzfile(file, "rb") : cannot open the connection
ERROR: lazy loading failed for package ‘ReactomePA’
* removing ‘/home/chenx/R/x86_64-pc-linux-gnu-library/3.5/ReactomePA’
Could you help me ?

**Comment by GuangchuangYu** [comment]
>cannot open compressed file '/home/chenx/R/x86_64-pc-linux-gnu-library/3.5/graphite/R/sysdata.rdx', probable reason 'No such file or directory'

reinstall `graphite`.
