### ISSUE TITLE
Working with more than one gene list

### ISSUE THREAD

**Issue by kasumaz** [GuangchuangYu/ReactomePA#22]
Dear Developers. 
The package is perfect. I can have it up and running for my own list of genes. 
What i would like to know is if there is a straightforward means to to sample more than 1 gene list and compare the pathways and visualiise them on barplot or dotplot. This is because I have gene lists for condition 1, condition 2, condition 3, etc. 

Would you happen to have a script that I can test out for more than 1 gene lists (that i can adapt) so that they can be compared? This would be super helpful. 
I am excited to use this tool. 
Thanks, Kaz

**Comment by GuangchuangYu** [comment]
you can use the `compareCluster()` function in the `clusterProfiler` package, see also <https://pubmed.ncbi.nlm.nih.gov/34557778/>.
