### ISSUE TITLE
one gene kills the pathway

### ISSUE THREAD

**Issue by under-score** [GuangchuangYu/ReactomePA#23]
`enrichPathway(gene=gene, readable=TRUE)`
finds something by
`gene <- c(10144, 80230,26240,152926,2020,26011,51133,152742)`
but not with
`gene <- c(10144, 80230,26240,152926,2020,26011,51133,152742,284076)`

**Comment by under-score** [comment]
?

**Comment by GuangchuangYu** [comment]
We expect the outputs are different as their inputs are different. 

For this specific case, it can be something like, from p=0.49 to p=0.51. 

You need to provide evidence that there is indeed an issue in `enrichPathway`.
