### ISSUE TITLE
support for plants?

### ISSUE THREAD

**Issue by Polligator** [GuangchuangYu/ReactomePA#28]
Hi there,

Hope you can help me figure out what was wrong. I tried to use the gsePathway function to analyze some RNA-seq data from maize, I first ranked the genes (using metrics: -log10(padj) * sign(log2FoldChange)), then loaded the ReactomePA package, used command:

Reactomeresult <- gsePathway(genelist, organism = "zma", pAdjustMethod = "BH",  minGSSize = 10, maxGSSize = 1000, pvalueCutoff=0.05)
 
I got an error:
character(0) 
Failed with error:  ‘'package' must be of length 1’

I googled the problem, seems like it's due to the lack of support for maize, but I see that the plant reactome is available, 
https://plantreactome.gramene.org/index.php?lang=en
just wonder if the support for plant species will be added, is there any other ways to do this kind of analysis before that becomes available?

Thanks very much for your time!

**Comment by GuangchuangYu** [comment]
You can use the universal interface implemented in clusterProfiler, see <https://www.sciencedirect.com/science/article/pii/S2666675821000667>.
