### ISSUE TITLE
installation from Github

### ISSUE THREAD

**Issue by YulongNiu** [GuangchuangYu/ReactomePA#3]
The installation from Github may need the R package `devtools`. 
How about

```
devtools::install_github(c("GuangchuangYu/DOSE", "GuangchuangYu/ReactomePA"))
```

?

**Comment by GuangchuangYu** [comment]
so?

**Comment by YulongNiu** [comment]
I think you may want to change it in the `README.md` that loading the `devtools` package in an explicit way.

**Comment by GuangchuangYu** [comment]
OK.
