### ISSUE TITLE
No gene can be mapped with gsePathway

### ISSUE THREAD

**Issue by alexandrafleming** [GuangchuangYu/ReactomePA#32]
Hello,

I am trying to run reactomePA for my DE genes. I manage to run enrichPathway successfully (`yy = enrichPathway(genes$entrezgene_id, pvalueCutoff=0.05)`), 
but when I do the following:

```
sorted_genes = sort(genes$entrezgene_id, decreasing = TRUE)
gseP = gsePathway(sorted_genes, organism = "human", pvalueCutoff = 0.05, pAdjustMethod = "BH", verbose = TRUE)
```

I am getting this error:

preparing geneSet collections...
--> Expected input gene ID: 1072,2768,3804,3479,3659,5742
Error in check_gene_id(geneList, geneSets) : 
  --> No gene can be mapped....

What could cause this issue?

Also the reactomePA manual page is not available: https://guangchuangyu.github.io/ReactomePA/ Is there somewhere else the manual? 
And a last question: Could I run the reactomePA analysis with my background set of genes?

Thank you in advance!
Kind regards,
Alex

**Comment by Kaixin-Huang** [comment]
I think the ReactomePA manual is here. Please check Chapter9: Reactome enrichment. [https://yulab-smu.top/biomedical-knowledge-mining-book/reactomepa.html](url)

**Comment by alexandrafleming** [comment]
Thank you for you reply.
