### ISSUE TITLE
Error in ReactomePA

### ISSUE THREAD

**Issue by aankit01-art** [GuangchuangYu/ReactomePA#4]
I am using R package for ReactomePA. But I am getting this type of error after reading each command perfectly also.

Error in x[seq_len(n)] : object of type 'S4' is not subsettable

Thanks!

**Comment by GuangchuangYu** [comment]
duplicated, see https://support.bioconductor.org/p/84708/

**Comment by aankit01-art** [comment]
But can you please help in solving my error ? I am using this package.

**Comment by GuangchuangYu** [comment]
already answered in bioconductor support site.
