### ISSUE TITLE
feature request: Mapping of Metabolites

### ISSUE THREAD

**Issue by topialla** [GuangchuangYu/ReactomePA#5]
Dear Guangchuang,
thanks for giving this nice package to the world ;-)

However, to be only able to map genes/proteins deprecates the full power of Reactome.
Could you think of a possibility to map metabolites as well?

Best, Tobias

**Comment by GuangchuangYu** [comment]
we use bioconductor package, https://bioconductor.org/packages/reactome.db/
for reactome data mapping. It seems that the package doesn't contain
metabolites data.

On Sat, Jul 2, 2016 at 12:02 AM, topiwan notifications@github.com wrote:

> Dear Guangchuang,
> thanks for giving this nice package to the world ;-)
> 
> However, to be only able to map genes/proteins deprecates the full power
> of Reactome.
> Could you think of a possibility to map metabolites as well?
> 
> Best, Tobias
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/GuangchuangYu/ReactomePA/issues/5, or mute the thread
> https://github.com/notifications/unsubscribe/AAmPa1PhkErHCD-XSxbFXhPBigGbBsCBks5qRTozgaJpZM4JDRkJ
> .

## 

--~--~---------~--~----~------------~-------~--~----~
Guangchuang Yu, PhD Candidate
State Key Laboratory of Emerging Infectious Diseases
School of Public Health
The University of Hong Kong
Hong Kong SAR, China
www: https://guangchuangyu.github.io
-~----------~----~----~----~------~----~------~--~---
