### ISSUE TITLE
Exporting getDb

### ISSUE THREAD

**Issue by LiNk-NY** [GuangchuangYu/ReactomePA#6]
Hi @GuangchuangYu,

Is the function `getDb` meant to be exported? It is not currently in the NAMESPACE and it seems like it should since other packages are depending on it. I got an error message that said: 

```
Error : object ‘getDb’ is not exported by 'namespace:GOSemSim' ERROR: lazy loading failed for package ‘ReactomePA’
```

when installing `ReactomePA` as a package dependency. 

Regards, 
Marcel

**Comment by GuangchuangYu** [comment]
you are using devel branch of `GOSemSim`, then you need to use corresponding branch of `DOSE` and `ReactomePA`.

``` r
devtools::install_bioc(c("DOSE", "ReactomePA"))
```

**Comment by LiNk-NY** [comment]
I am using bioc-devel. You are missing an `@export` tag on `getDb`.

**Comment by GuangchuangYu** [comment]
it was move to ReactomePA, see https://github.com/GuangchuangYu/ReactomePA/blob/master/R/utilities.R

**Comment by LiNk-NY** [comment]
Yes, I see that. You need to export this function from `ReactomePA`. 

`BiocInstaller::biocLite("ReactomePA")` returns an error: 

```
Error : object ‘getDb’ is not exported by 'namespace:GOSemSim'
ERROR: lazy loading failed for package ‘ReactomePA’
```

We know it's not exported from `GOSemSim` because it was moved to `ReactomePA`. It can't be found because it's not exported in the `ReactomePA` NAMESPACE.

**Comment by GuangchuangYu** [comment]
it's not used elsewhere. Why I need to export it ?

**Comment by LiNk-NY** [comment]
Hi @GuangchuangYu,
If it is meant to be internal then you don't need to document it. What I usually do is add a period ('.') in front of the function so that it isn't picked up as an object that  should be documented and exported by the checks. 
This will resolve the error that appears when installing.

**Comment by GuangchuangYu** [comment]
the issue is due to mixing installation of release and devel branch and not related to the documentation and function name.

**Comment by LiNk-NY** [comment]
The version number has not been updated and thus the package in the Bioc servers is not being re-build properly with the new changes please bump your version so that the package can be installed via `BiocInstaller::biocLite("ReactomePA")`

See #7 

Regards,
Marcel

**Comment by GuangchuangYu** [comment]
by default, `BiocInstaller::biocLite("ReactomePA")` will always install the release version.

In `release` branch, `ReactomePA` is still import `getDb` from `GOSemSim`.

Here, we are talking about the `devel` branch. You need to install it by:

``` r
library(BiocInstaller)
useDevel()
biocLite("ReactomePA")
```

Referring to https://github.com/GuangchuangYu/ReactomePA/issues/7, you need to wait 2-3 days for Bioconductor to update tarball or use `devtools::install_bioc()` to install it from svn repository as I also mentioned in https://github.com/ManuelGoepferich/LINC/issues/1#issuecomment-237126811.

**Comment by LiNk-NY** [comment]
Yes, I know that. I'm using and have been using the devel version of Bioconductor for a while now. Even using the devel branch, that error appears which indicates that your changes haven't been propagated due to the version bump issue. 
Thanks for updating that.
