### ISSUE TITLE
bump version

### ISSUE THREAD

**Issue by LiNk-NY** [GuangchuangYu/ReactomePA#7]
Your version number hasn't been bumped since Dan bumped it automatically in March. 

```
r117512 | d.tenenbaum | 2016-05-15 16:14:22 -0400 (Sun, 15 May 2016) | 6 lines
```

This means that the changes you have made via SVN have not been propagated in the server. 
In other words, `BiocInstaller::biocLite("ReactomePA")` is not working properly from the `devel` branch.

**Comment by GuangchuangYu** [comment]
[done](https://github.com/GuangchuangYu/ReactomePA/commit/87e733a30af79aec02007a7a8ad664717c7cf068) and also see https://github.com/ManuelGoepferich/LINC/issues/1#issuecomment-237126811
