### ISSUE TITLE
very different results with upgrade of R

### ISSUE THREAD

**Issue by psudmant** [GuangchuangYu/ReactomePA#9]
I recently updated from R 3.2.2 to 3.3.1 and the enrichPathway result is very very different for the identical list of genes. The P-values are different by about 3 orders of magnitude and while the returned result is similar, the order is quite a bit different. The problem is very difficult to figure out however because I can reproduce 2 totally different results on 3 different computers using the same gene set, and yet, it's not even clear to me exactly what package being used by enrichPathway is causing the issue. Any suggestions?  

Here are three different sessionInfos with 2 different results:

Original EnrichPathway Result (result 1) (R3.2.2 running on computer 1)
AnnotationDbi_1.32.3
Biobase_2.30.0
BiocGenerics_0.16.1
BiocInstaller_1.20.3
DOSE_2.9.1
IRanges_2.4.8
ReactomePA_1.14.4
clusterProfiler_2.4.3
org.Mm.eg.db_3.2.3

New different EnrichPathway Result (result 2) (R3.2.2 running on computer 2)
AnnotationDbi_1.32.3
Biobase_2.30.0
BiocGenerics_0.16.1
BiocInstaller_1.20.3
DOSE_2.8.3
IRanges_2.4.8
ReactomePA_1.14.4
clusterProfiler_2.4.3
org.Mm.eg.db_3.2.3

New different EnrichPathway Result (result 2) (R3.2.3 running on computer 3)
AnnotationDbi_1.35.4
Biobase_2.33.3
BiocGenerics_0.19.2
BiocInstaller_1.22.3
DOSE_2.11.12
IRanges_2.7.16
ReactomePA_1.17.4
clusterProfiler_3.1.8
org.Mm.eg.db_3.4.0

**Comment by GuangchuangYu** [comment]
You should rely on the new version.

Old version has some issues due to [inaccurate `reactome.db`](https://support.bioconductor.org/p/63024/). `ReactomePA` itself has no problem.
